name    'musaic-vim'
version '2.0.0'
source 'git://github.com/musaic/puppet-module-vim.git'
author 'musaic'
license 'Apache License, Version 2.0'
summary 'Manage everyone\'s favorite editor, Vim.'
description 'Manage Vim'
project_page 'https://github.com/musaic/puppet-module-vim'

dependency 'puppetlabs/stdlib', '>= 4.0.x'
