#!/usr/bin/env zsh -f
#
#

list=(
https://github.com/altercation/vim-colors-solarized.git
https://github.com/tpope/pry-editline.git
https://github.com/tpope/vim-abolish.git
#https://github.com/tpope/vim-afterimage.git
https://github.com/tpope/vim-bundler.git
#https://github.com/tpope/vim-capslock.git
https://github.com/tpope/vim-characterize.git
#https://github.com/tpope/vim-classpath.git
https://github.com/tpope/vim-commentary.git
https://github.com/tpope/vim-cucumber.git
#https://github.com/tpope/vim-dispatch.git
#https://github.com/tpope/vim-endwise.git
#https://github.com/tpope/vim-eunuch.git
#https://github.com/tpope/vim-fireplace.git
#https://github.com/tpope/vim-flatfoot.git
#https://github.com/tpope/vim-foreplay.git
https://github.com/tpope/vim-fugitive.git
https://github.com/tpope/vim-git.git
#https://github.com/tpope/vim-haml.git
https://github.com/tpope/vim-liquid.git
https://github.com/tpope/vim-markdown.git
https://github.com/tpope/vim-obsession.git
https://github.com/tpope/vim-pastie.git
https://github.com/tpope/vim-pathogen.git
#https://github.com/tpope/vim-ragtag.git
#https://github.com/tpope/vim-rails.git
https://github.com/tpope/vim-rake.git
https://github.com/tpope/vim-rbenv.git
https://github.com/tpope/vim-repeat.git
#https://github.com/tpope/vim-rhubarb.git
#https://github.com/tpope/vim-rsi.git
#https://github.com/tpope/vim-rvm.git
https://github.com/tpope/vim-scriptease.git
# https://github.com/tpope/vim-sensible.git
# https://github.com/tpope/vim-sleuth.git
https://github.com/tpope/vim-speeddating.git
https://github.com/tpope/vim-surround.git
https://github.com/tpope/vim-tbone.git
https://github.com/tpope/vim-unimpaired.git
https://github.com/tpope/vim-vividchalk.git
https://github.com/rodjek/vim-puppet.git
)

for i in ${list}; do {
  [[ ! -d bundle/${i:r:t} ]] && git clone $i bundle/${i:r:t}
} done

